### ISSUE TITLE
can not find library .a file, I also pod the two file in the Podefile. the ,a file is not exist

### ISSUE THREAD

**Issue by ioslaozhao** [kevin0571/STPopupPreview#1]
ld: library not found for -lSTPopup

**Comment by kevin-lyn** [comment]
@zkf63858 Did you open the .workspace file after pod install?

**Comment by ioslaozhao** [comment]
Yes,libSTPopup.a and libSTPopupPreview.a not exist.

发自我的 iPhone

**Comment by ioslaozhao** [comment]
Target 'Pods-LawChat' of project 'Pods' was rejected as an implicit dependency for 'libPods-LawChat.a' because its architectures 'x86_64' didn't contain all required architectures 'i386 x86_64'

ld: warning: directory not found for option '-L/Users/lielvwang/Library/Developer/Xcode/DerivedData/LawChat-ehujirtoevlsvucyaqwslijfnqob/Build/Products/Debug-iphonesimulator/STPopup'
ld: warning: directory not found for option '-L/Users/lielvwang/Library/Developer/Xcode/DerivedData/LawChat-ehujirtoevlsvucyaqwslijfnqob/Build/Products/Debug-iphonesimulator/STPopupPreview'
ld: warning: directory not found for option '-L/Users/lielvwang/Documents/sys/LawChat/build/Debug-iphoneos/STPopup'
ld: warning: directory not found for option '-L/Users/lielvwang/Documents/sys/LawChat/build/Debug-iphoneos/STPopupPreview'
ld: warning: directory not found for option '-L/Users/lielvwang/Documents/sys/LawChat/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/lielvwang/Documents/sys/LawChat/LawChat/LawChat/3th/STPopup'
ld: library not found for -lSTPopup
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kevin-lyn** [comment]
@zkf63858 can you try to remove Podfile.lock and re-run pod install.
