### ISSUE TITLE
Q&A - The error 'contentSizeInPopup should not be size zero'

### ISSUE THREAD

**Issue by kailuu5495** [kevin0571/STPopupPreview#3]
Sorry to bother you, but I can't use the STPopopPreview in my project. Please help me fix it ! Thank you so much ! 
![screen shot 2016-09-12 at 5 06 44 pm](https://cloud.githubusercontent.com/assets/20751724/18432362/b57b3884-790b-11e6-8daf-513089a04b5f.png)

**Comment by kevin-lyn** [comment]
@KaiLuu you need to set the contentSizeInPopup for "DetailVC", for usage of STPopup please refer to  http://github.com/kevin0571/STPopup

**Comment by Sea-Eagle** [comment]
I'm also getting same error. where should I set "contentSizeInPopup". In the view controller where we need to show bottom style popup view or the view controller which is showing as popup
