### ISSUE TITLE
3D Touch usage for iphone 6s and above

### ISSUE THREAD

**Issue by calvinsug** [kevin0571/STPopupPreview#7]
If i'm not mistaken, this library applies on iphone which doesn't have 3D touch. How about iphone 6S and above ? It does have 3D touch, can i use this library to preview my image? Or should i put different code applied for it's 3D touch function ?

**Comment by kevin-lyn** [comment]
For device which supports 3D touch, you could still use this library to preview image. The preview popup will still be shown with long press gesture. But this is actually not suggested because 3D touch interaction is still better and recommended if the device does support it.
